apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-keeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: key-keeper
  template:
    metadata:
      labels:
        app: key-keeper
    spec:
      containers:
        - name: key-keeper
          image: qbchak/key-keeper:0.1.4-SNAPSHOT
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: docker-hub-secret
