---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-keeper
spec:
  selector:
    matchLabels:
      app: key-keeper
  replicas: 3
  template:
    metadata:
      labels:
        app: key-keeper
    spec:
      containers:
        - name: key-keeper
          image: qbchak/key-keeper:0.1.5-SNAPSHOT
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: docker-hub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: key-keeper
  labels:
    app: key-keeper
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: key-keeper