apiVersion: v1
kind: Pod
metadata:
  name: key-keeper
  labels:
    app: key-keeper
spec:
  containers:
    - name: key-keeper
      image: qbchak/key-keeper:0.1.4-SNAPSHOT
      ports:
        - containerPort: 8080
      env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "docker"
        - name: DB_PASSWORD
          value: "docker"
        - name: DB_NAME
          value: "board"
  imagePullSecrets:
    - name: docker-hub-secret

---

apiVersion: v1
kind: Service
metadata:
  name: key-keeper-service
spec:
  selector:
    app: key-keeper
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort