name: CD

on:
  workflow_run:
    workflows: [ CI ]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest
      - name: Configure kubectl with Secrets
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CA }}" | base64 --decode > $HOME/.kube/ca.crt
          echo "${{ secrets.KUBE_CLIENT_CERT }}" | base64 --decode > $HOME/.kube/client.crt
          echo "${{ secrets.KUBE_CLIENT_KEY }}" | base64 --decode > $HOME/.kube/client.key

          kubectl config set-cluster minikube-cluster --server=${{ secrets.KUBE_HOST }} --certificate-authority=$HOME/.kube/ca.crt
          kubectl config set-credentials minikube-user --client-certificate=$HOME/.kube/client.crt --client-key=$HOME/.kube/client.key
          kubectl config set-context minikube-context --cluster=minikube-cluster --user=minikube-user
          kubectl config use-context minikube-context
          kubectl config view  # Debug step to verify kubectl configuration
      - name: Get Pods
        run: kubectl get pods
