name: CD
on:
  workflow_run:
    workflows: [ CI ]
    types:
      - completed
jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest
        id: install
      - name: Configure kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBECONFIG" | base64 -d > kubeconfig.yaml 
          cat kubeconfig.yaml 
          export KUBECONFIG=$(pwd)/kubeconfig.yaml 
          kubectl config view 
      - name: Update Kubernetes Deployment Image
        run: |
          kubectl set image deployment/key-keeper \
          key-keeper=${{ secrets.DOCKER_USERNAME }}/key-keeper:latest
      - name: Verify Deployment
        run: kubectl rollout status deployment/key-keeper